<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Moyentp extends \App\Entity\Moyentp implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'matricule', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'nbreplace', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'prix_ticket', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'horaire', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'moyentp'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'matricule', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'nbreplace', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'prix_ticket', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'horaire', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Moyentp' . "\0" . 'moyentp'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Moyentp $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule(string $matricule): \App\Entity\Moyentp
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$matricule]);

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): \App\Entity\Moyentp
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreplace(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreplace', []);

        return parent::getNbreplace();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreplace(int $nbreplace): \App\Entity\Moyentp
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreplace', [$nbreplace]);

        return parent::setNbreplace($nbreplace);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixTicket(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixTicket', []);

        return parent::getPrixTicket();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixTicket(float $prix_ticket): \App\Entity\Moyentp
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixTicket', [$prix_ticket]);

        return parent::setPrixTicket($prix_ticket);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraire(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraire', []);

        return parent::getHoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraire(string $horaire): \App\Entity\Moyentp
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraire', [$horaire]);

        return parent::setHoraire($horaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Moyentp
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoyentp(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoyentp', []);

        return parent::getMoyentp();
    }

    /**
     * {@inheritDoc}
     */
    public function addMoyentp(\App\Entity\Ligne $moyentp): \App\Entity\Moyentp
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMoyentp', [$moyentp]);

        return parent::addMoyentp($moyentp);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMoyentp(\App\Entity\Ligne $moyentp): \App\Entity\Moyentp
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMoyentp', [$moyentp]);

        return parent::removeMoyentp($moyentp);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
