<?php

namespace ContainerQcOn8qJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WUzyJh8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wUzyJh8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wUzyJh8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'guide' => ['privates', '.errored..service_locator.wUzyJh8.App\\Entity\\Guide', NULL, 'Cannot autowire service ".service_locator.wUzyJh8": it references class "App\\Entity\\Guide" but no such service exists.'],
        ], [
            'guide' => 'App\\Entity\\Guide',
        ]);
    }
}
