<?php

namespace ContainerQcOn8qJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZnepDYZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZnepDYZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZnepDYZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ligne' => ['privates', '.errored..service_locator.ZnepDYZ.App\\Entity\\Ligne', NULL, 'Cannot autowire service ".service_locator.ZnepDYZ": it references class "App\\Entity\\Ligne" but no such service exists.'],
            'ligneRepository' => ['privates', 'App\\Repository\\LigneRepository', 'getLigneRepositoryService', true],
        ], [
            'ligne' => 'App\\Entity\\Ligne',
            'ligneRepository' => 'App\\Repository\\LigneRepository',
        ]);
    }
}
