<?php

namespace ContainerQcOn8qJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RHozOkBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RHozOkB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RHozOkB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'GuideRepository' => ['privates', 'App\\Repository\\GuideRepository', 'getGuideRepositoryService', true],
        ], [
            'GuideRepository' => 'App\\Repository\\GuideRepository',
        ]);
    }
}
