<?php

namespace ContainerQcOn8qJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JlvkeaaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jlvkeaa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jlvkeaa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'moyentp' => ['privates', '.errored..service_locator.Jlvkeaa.App\\Entity\\Moyentp', NULL, 'Cannot autowire service ".service_locator.Jlvkeaa": it references class "App\\Entity\\Moyentp" but no such service exists.'],
            'moyentpRepository' => ['privates', 'App\\Repository\\MoyentpRepository', 'getMoyentpRepositoryService', true],
        ], [
            'moyentp' => 'App\\Entity\\Moyentp',
            'moyentpRepository' => 'App\\Repository\\MoyentpRepository',
        ]);
    }
}
