<?php

namespace ContainerQcOn8qJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuide2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wUzyJh8.App\Entity\Guide' shared service.
     *
     * @return \App\Entity\Guide
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.wUzyJh8": it references class "App\\Entity\\Guide" but no such service exists.');
    }
}
