<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQcOn8qJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQcOn8qJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQcOn8qJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQcOn8qJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQcOn8qJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'QcOn8qJ',
    'container.build_id' => '437f6126',
    'container.build_time' => 1683064312,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQcOn8qJ');
