<?php

namespace ContainerN2LLgSN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VjLHagrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VjLHagr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VjLHagr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'guide' => ['privates', '.errored..service_locator.VjLHagr.App\\Entity\\Guide', NULL, 'Cannot autowire service ".service_locator.VjLHagr": it references class "App\\Entity\\Guide" but no such service exists.'],
            'guideRepository' => ['privates', 'App\\Repository\\GuideRepository', 'getGuideRepositoryService', true],
        ], [
            'guide' => 'App\\Entity\\Guide',
            'guideRepository' => 'App\\Repository\\GuideRepository',
        ]);
    }
}
