<?php

namespace ContainerN2LLgSN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1jyyPFxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1jyyPFx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1jyyPFx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'location' => ['privates', '.errored..service_locator.1jyyPFx.App\\Entity\\Location', NULL, 'Cannot autowire service ".service_locator.1jyyPFx": it references class "App\\Entity\\Location" but no such service exists.'],
            'locationRepository' => ['privates', 'App\\Repository\\LocationRepository', 'getLocationRepositoryService', true],
        ], [
            'location' => 'App\\Entity\\Location',
            'locationRepository' => 'App\\Repository\\LocationRepository',
        ]);
    }
}
