<?php

namespace ContainerN2LLgSN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChauffeurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ef8xEl6.App\Entity\Chauffeur' shared service.
     *
     * @return \App\Entity\Chauffeur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Ef8xEl6": it references class "App\\Entity\\Chauffeur" but no such service exists.');
    }
}
