<?php

namespace ContainerN2LLgSN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NX2vl8V.App\Entity\Ligne' shared service.
     *
     * @return \App\Entity\Ligne
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.NX2vl8V": it references class "App\\Entity\\Ligne" but no such service exists.');
    }
}
