<?php

namespace ContainerN2LLgSN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoyentpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Jlvkeaa.App\Entity\Moyentp' shared service.
     *
     * @return \App\Entity\Moyentp
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Jlvkeaa": it references class "App\\Entity\\Moyentp" but no such service exists.');
    }
}
